### PR TITLE
Initial Adoption of Continous Deployment using semantic-release

### PR DESCRIPTION
**Pull request by keplersj**
To ease the modification/contribution to publish pipeline there has been some discussion of adopting a continuous deployment system for AtomLinter packages. To accomplish this we are making use of [`semantic-release`](https://github.com/semantic-release/semantic-release) and [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config).

This pull request has been [dynamically created using a script](https://gist.github.com/keplersj/8bc7622ea741c0964d12842bfc679c5d). While the result is not perfect, it does accompish most of the grunt work of adopting continous deployment. There is some reconciliation that needs to be done before this can be merged.

Among the things needed to be reconciled, an [APM Token](https://atom.io/account) and [GitHub Token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) will need to be added to this repo's continous integration (most likely [Travis CI](https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings)) configuration for automated deployments to work.

Again, this Pull Request has been created by a script made by @keplersj. Please mention him if something has gone wrong, and he'll be happy to help.

ref: AtomLinter/Meta#18

cc: @Arcanemagus

### CODE REVIEW

**Comment by Arcanemagus** [comment]
It looks like this project _has_ no CI, so it's not an issue that this was merged without configuring that.

**Comment by keplersj** [comment]
The [Travis CI config from `ide-crystal`](https://github.com/crystal-lang-tools/atom-ide-crystal/blob/master/.travis.yml) would probably be a very basic one to use. Feel free to steal it. 😁

**Comment by RetroCraft** [comment]
I've stolen that `.travis.yml`, not sure exactly how to setup Travis though. I assume something has to be done on the organization's end.

**Comment by Arcanemagus** [comment]
image

Done 😉.

**Comment by Arcanemagus** [comment]
It looks like you have admin rights on this repo, so I _think_ you might be able to edit the settings of the repository on Travis CI, feel free to message me on Atom's Slack if not and you need something changed though!

**Pull request merged**
